# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./.docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf:ro
      - app:/var/www/html
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/var/www/html
    environment:
      - APP_ENV=prod

volumes:
  app: