version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORTS}"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORTS}"

  nginx:
    container_name: nginx
    image: nginx:1.25-alpine3.17
    ports:
     - "${NGINX_PORTS}"
    volumes:
      - "./client/nginx.conf:/etc/nginx/conf.d/default.conf"


